# Generated by Django 5.1.4 on 2024-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('task_app', '0003_alter_task_groups_alter_task_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(related_name='task_groups', related_query_name='task', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_permissions',
            field=models.ManyToManyField(related_name='task_user_permissions', related_query_name='task', to='auth.permission'),
        ),
    ]
